import React, { createContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

export const locales = {
  vi: {
    setting: "Cài Đặt",
    logout: "Đăng Xuất",
    changePassword: "Đổi Mật Khẩu",
    notifications: "Tắt thông báo",
    language: "Ngôn Ngữ",
    mode: "Chế Độ",
    contacts: "Danh Bạ",
    search: "Tìm Kiếm",
    friendRequest: "Lời mời kết bạn",
    noFriendRequest: "Không có lời mời kết bạn nào.",
    friendList: "Danh sách bạn bè",
    login: "Đăng Nhập",
    loginSuccess: "Đăng Nhập Thành Công",
    loginError: "Đăng Nhập Thất Bại",
    register: "Đăng Ký",
    forgotPassword: "Quên Mật Khẩu",
    sendResetLink: "Gửi liên kết đặt lại mật khẩu",
    confirmEmail: "Xác Nhận Email",
    resetPassword: "Đặt Lại Mật Khẩu",
    PhoneNumber: "Số Điện Thoại",
    Password: "Mật Khẩu",
    confirmPassword: "Xác Nhận Mật Khẩu",
    oldPassword: "Mật Khẩu Cũ",
    newPassword: "Mật Khẩu Mới",
    replatePassword:"Xác Nhận Mật Khẩu",
    notAccount: "Bạn chưa có tài khoản?",
    haveAccount: "Bạn đã có tài khoản?",
    email: "Email",
    userName: "Tên Người Dùng",
    loadingRegister: "Đang Đăng Ký...",
    forgotPasswordSuccess: "Đặt lại mật khẩu thành công. Vui lòng kiểm tra email của bạn.",
    forgotPasswordError: "Đặt lại mật khẩu thất bại. Vui lòng thử lại.",
    linkSetPass: "Gửi link đặt lại mật khẩu",
    linkSetPassSuccess: "Gửi link đặt lại mật khẩu thành công.",
    linkSetPassError: "Gửi link đặt lại mật khẩu thất bại. Vui lòng thử lại.",
    linkSetPassEmail: "Vui lòng kiểm tra email của bạn để nhận liên kết đặt lại mật khẩu.",
    linkSetPassErrorEmail: "Gửi link đặt lại mật khẩu thất bại. Vui lòng kiểm tra email của bạn.",
    linkding: "Đang tải...",
    invalidPhone: "Số điện thoại phải có đúng 10 chữ số.",
    invalidEmail: "Email không hợp lệ.",
    invalidPassword: "Mật khẩu phải có ít nhất 6 ký tự, bao gồm ít nhất một chữ cái và một số.",
    invalidUsername: "Tên người dùng phải có ít nhất 3 ký tự, không có khoảng trắng ở đầu, và chỉ chứa chữ cái hoặc số.",
    rePass: "Mật khẩu không khớp.",
    inforAccount: "Thông tin tài khoản",
    name: "Tên",
    birthday: "Ngày sinh",
    updateAvatar: "Cập nhật ảnh đại diện",
    cancel: "Hủy",
    save: "Lưu",
    sex: "Giới tính",
    phone: "Điện thoại",
    male: "Nam",
    female: "Nữ",
    unknown: "Chưa xác định",
    perInfor: "Thông tin cá nhân",
    updateInfor: "Cập nhật thông tin",
    updateInforSuccess: "Cập nhật thông tin thành công",
    updateInforError: "Cập nhật thông tin thất bại",
    day: "Ngày",
    month: "Tháng",
    year: "Năm",
    selectSex: "Chọn giới tính",
    notToken: "Không có mã xác thực",
    title: "Tạo Nhóm",
    groupName: "Tên nhóm",
    groupNamePlaceholder: "Nhập tên nhóm...",
    noFriends: "Không có bạn bè nào.",
    friendsToAdd: "Những người bạn có thể thêm vào nhóm",
    createGroup: "Tạo nhóm",
    invalidNameGroup: "Tên nhóm không hợp lệ.",
    minMembersGroup: "Một nhóm phải có ít nhất ba thành viên.",
    createGroupSuccess: "Tạo nhóm thành công!",
    createGroupFailed: "Tạo nhóm thất bại!",
    unfriend: "Hủy Kết Bạn",
    unfriendSuccess: "Hủy kết bạn thành công!",
    unfriendFailed: "Hủy kết bạn thất bại!",
    acceptFriendRequest: "Chấp Nhận",
    notFriendRequest: "Không có lời mời kết bạn nào.",
    rejectFriendRequest: "Từ Chối",
    listFriend: "Danh sách bạn bè",
    noFriend: "Không có bạn bè nào.",
    addFriend: "Thêm bạn bè",
    deleteConversation: "Xóa cuộc trò chuyện",
    deleteConversationSuccess: "Xóa cuộc trò chuyện thành công",
    deleteConversationFailed: "Xóa cuộc trò chuyện thất bại",
    notConversation: "Hãy tìm bạn bè bằng số điện thoại và trò chuyện với họ ngay nào!",
    notConversation2: "Chưa có cuộc trò chuyện nào",
    vi: "Tiếng Việt",
    en: "Tiếng Anh",
    dark: "Chế độ tối",
    light: "Chế độ sáng",
    updateImage: 'Cập nhật ảnh',

  },
  en: {
    setting: "Settings",
    logout: "Logout",
    changePassword: "Change Password",
    notifications: "Notifications",
    language: "Language",
    mode: "Mode",
    contacts: "Contacts",
    search: "Search",
    friendRequest: "Friend Requests",
    noFriendRequest: "No friend requests.",
    friendList: "Friend List",
    login: "Login",
    loginSuccess: "Login Successful",
    loginError: "Login Failed",
    register: "Register",
    forgotPassword: "Forgot Password",
    sendResetLink: "Send Reset Link",
    confirmEmail: "Confirm Email",
    resetPassword: "Reset Password",
    PhoneNumber: "Phone Number",
    Password: "Password",
    confirmPassword: "Confirm Password",
    oldPassword: "Old Password",
    newPassword: "New Password",
    replatePassword: "Re-enter Password",
    notAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    email: "Email",
    userName: "Username",
    loadingRegister: "Registering...",
    forgotPasswordSuccess: "Password reset successful. Please check your email.",
    forgotPasswordError: "Password reset failed. Please try again.",
    linkSetPass: "Send password reset link",
    linkSetPassSuccess: "Password reset link sent successfully.",
    linkSetPassError: "Failed to send password reset link. Please try again.",
    linkSetPassEmail: "Please check your email for the password reset link.",
    linkSetPassErrorEmail: "Failed to send password reset link. Please check your email.",
    linkding: "Loading...",
    invalidPhone: "Phone number must be exactly 10 digits.",
    invalidEmail: "Invalid email address.",
    invalidPassword: "Password must be at least 6 characters, including at least one letter and one number.",
    invalidUsername: "Username must be at least 3 characters, no leading spaces, and only letters or numbers.",
    rePass: "Passwords do not match.",
    infoAccount: "Account Information",
    name: "Name",
    birthday: "Birthday",
    updateAvatar: "Update Avatar",
    cancel: "Cancel",
    save: "Save",
    sex: "Gender",
    phone: "Phone",
    male: "Male",
    female: "Female",
    unknown: "Unknown",
    perInfor: "Personal Information",
    updateInfor: "Update Information",
    updateInforSuccess: "Information updated successfully",
    updateInforError: "Failed to update information",
    day: "Day",
    month: "Month",
    year: "Year",
    selectSex: "select gender",
    notToken: "No verification code",
    title: "Create Group",
    groupName: "Group Name",
    groupNamePlaceholder: "Enter group name...",
    noFriends: "No friends available.",
    friendsToAdd: "Friends you can add to the group",
    createGroup: "Create Group",
    invalidNameGroup: "Invalid group name.",
    minMembersGroup: "A group must have at least three members.",
    createGroupSuccess: "Group created successfully!",
    createGroupFailed: "Failed to create group!",
    unfriend: "Unfriend",
    unfriendSuccess: "Unfriend successful!",
    unfriendFailed: "Failed to unfriend!",
    acceptFriendRequest: "Accept",
    notFriendRequest: "No friend requests.",
    rejectFriendRequest: "Reject",
    listFriend: "Friends List",
    noFriend: "No friends available.",
    addFriend: "Add Friend",
    deleteConversation: "Delete Conversation",
    deleteConversationSuccess: "Conversation deleted successfully",
    deleteConversationFailed: "Failed to delete conversation",
    notConversation: "Find friends by phone number and start chatting with them now!",
    notConversation2: "No conversations yet",
    vi: "Vietnamese",
    en: "English",
    dark: "Dark Mode",
    light: "Light Mode",
    updateImage: 'Update Image',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "vi";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

